_wandb:
    value:
        cli_version: 0.22.3
        e:
            jb9rxvejw6q4kwitg0ezpi3w2d7vurat:
                args:
                    - --pretrained_mode=bert
                    - --word_embedding_dim=128
                    - --learning_rate=0.00001
                    - --dropout_probability=0.2
                    - --batch_size=16
                    - --finetune_layers=4
                codePath: baseline/bert/train.py
                codePathLocal: baseline/bert/train.py
                cpu_count: 72
                cpu_count_logical: 72
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "270185504768"
                        used: "5056270336"
                email: yitjunyam@hotmail.com
                executable: /home/scur1748/.conda/envs/newsrec/bin/python
                git:
                    commit: 4fcef6ec127b02151c908d23b10831760a6eda79
                    remote: git@github.com:MaxBomer/ir2-colbert-news.git
                gpu: NVIDIA A100-SXM4-40GB
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-SXM4-40GB
                      uuid: GPU-298979f0-6d3d-0977-9c83-1737c2ba55dc
                host: gcn33.local.snellius.surf.nl
                memory:
                    total: "540634988544"
                os: Linux-5.14.0-427.92.1.el9_4.x86_64-x86_64-with-glibc2.34
                program: /gpfs/home2/scur1748/ir2-colbert-news/baseline/bert/train.py
                python: CPython 3.9.25
                root: /gpfs/home2/scur1748/ir2-colbert-news
                slurm:
                    cluster_name: snellius
                    conf: /var/spool/slurm/slurmd/conf-cache/slurm.conf
                    cpu_bind: quiet,mask_cpu:0x0000000000000001FF
                    cpu_bind_list: "0x0000000000000001FF"
                    cpu_bind_type: 'mask_cpu:'
                    cpu_bind_verbose: quiet
                    cpus_on_node: "9"
                    cpus_per_task: "9"
                    distribution: cyclic
                    eclibr: "0"
                    ecplug: "1"
                    erlast: srun
                    ersbac: "1"
                    ersrun: "1"
                    export_env: ALL
                    get_user_env: "1"
                    gpus: "1"
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: gpuuva065
                    job_cpus_per_node: "18"
                    job_end_time: "1762721575"
                    job_gid: "63542"
                    job_gpus: "0"
                    job_id: "15842223"
                    job_name: TrainBaseline
                    job_nodelist: gcn33
                    job_num_nodes: "1"
                    job_partition: gpu_a100
                    job_qos: normal
                    job_start_time: "1762649575"
                    job_uid: "64008"
                    job_user: scur1748
                    jobid: "15842223"
                    launch_node_ipaddr: 172.18.62.33
                    localid: "0"
                    mpi_type: pmi2
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: gcn33
                    nprocs: "1"
                    ntasks: "1"
                    oom_kill_step: "0"
                    prio_process: "0"
                    procid: "0"
                    script_context: prolog_task
                    srun_comm_host: 172.18.62.33
                    srun_comm_port: "42549"
                    step_gpus: "0"
                    step_gres: gres/cpu:0
                    step_id: "0"
                    step_launcher_port: "42549"
                    step_nodelist: gcn33
                    step_num_nodes: "1"
                    step_num_tasks: "1"
                    step_resv_ports: 14774-14775
                    step_tasks_per_node: "1"
                    stepid: "0"
                    submit_dir: /gpfs/home2/scur1748/ir2-colbert-news
                    submit_host: int6.local.snellius.surf.nl
                    task_pid: "2238344"
                    tasks_per_node: "1"
                    topology_addr: root.ibsw4.gcn33
                    topology_addr_pattern: switch.switch.node
                    tres_per_task: cpu=9
                    umask: "0077"
                startedAt: "2025-11-09T00:53:26.265602Z"
                writerId: jb9rxvejw6q4kwitg0ezpi3w2d7vurat
        m: []
        python_version: 3.9.25
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 71
                - 100
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 71
                - 100
            "3":
                - 16
            "4": 3.9.25
            "5": 0.22.3
            "6": 4.57.1
            "12": 0.22.3
            "13": linux-x86_64
dropout_probability:
    value: 0.2
finetune_layers:
    value: 4
learning_rate:
    value: 1e-05
model:
    value: NRMSbert
pretrained_mode:
    value: bert
word_embedding_dim:
    value: 128
